### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MrTordse** [TeamGalacticraft/Galacticraft-Legacy#158]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.6

### Reproduction steps

Basically I have 2 different space stations in same dimension and every time i go build the new one after i come back with empty oxygen canisters my oxygen sealers are empty and complaining about "area too big or unsealed" then i almost die because i have no oxygen. This problem also happens in planets like mars when i go explore and come back the sealers dont work. The oxygen sealers however work fine when i land on my space station with a rocket and continue to work untill i go further away for some time. After i come back they dont even start to work if i stay, i need to break pipes and sometimes they still dont work untill the world is loaded again. I have tested this in tekkit2 modpack and original tekkit space modpack.

**Comment by ROMVoid95** [comment]
is the issue reproducible with only Galacticraft installed? If so, a little more information would be helpful.  

- referencing `after i come back with empty oxygen canisters my oxygen sealers are empty`, are you talking about the oxygen tanks in your equipment inventory? 
- Are the sealers supplied using a constant oxygen resupply method? or with a single oxygen tank directly  (Asking this since i'm not sure on the tank reference above)
  - *Ex: Tree room with collector that routes directly to sealers OR `collector` -> `storage block/clusters` -> `sealers`*
- If with a single tank, are the chunks the sealers are in being chunk loaded?
- Do they work again if the sealer itself is mined and placed back again?

**Comment by MrTordse** [comment]
I have not tested with only galacticraft because i tried to install only galacticraft like a year ago and would not get it to work no matter what probably due to not being very good with software stuff in general. With empty oxygen canisters i mean the ones in equipment inventory. Collectors----> 2 different storage blocks---->sealers. It seems that after i removed the oxygen storage blocks the oxygen sealers started to fill up faster but still when i go away and come back the oxygen system is empty and takes time to start having the oxygen in the sealers again. Breaking the sealer and re placing it didnt help and i dont have any chunk loaders. Seems like the oxygen collectors stop collecting or leaves stop producing oxygen when i go far away. This will be a problem as i plan on getting animals on my space station but they would die every time i travel.

**Comment by ROMVoid95** [comment]
It looks like the chunks are simply unloading, hence nothing in those chunks is going to function, that is an intended function of Minecraft. You would need to have a chunk loader to keep things running, that is, keeping the chunk loaded when it would normally be unloaded. Which loader you use is completely up to you. For a note: The Launch Controller acts as chunk loader for only the 1 chunk it is inside of, As long as its powered. Doesn't require a launchpad being adjacent to it.

**Comment by MrTordse** [comment]
Might be yes, but why does the oxygen system still continue to use the remaining oxygen until its empty if the chunks are unloaded?

**Comment by ROMVoid95** [comment]
chunks normally wouldn't unload right away
