### ISSUE TITLE
[Bug]: Crash on startup; The fluid registry is corrupted

### ISSUE THREAD

**Issue by Sir-Technical** [TeamGalacticraft/Galacticraft-Legacy#162]
### Forge Version

14.23.5.2854

### Galacticraft Version

Galacticraft-1.12.2-4.0.6

### Log or Crash Report

crash report: https://gist.github.com/Sir-Technical/45590914abd087c0d03f6b84803e93b1

latest log: https://gist.github.com/Sir-Technical/45ca4876e94c45420e737423b6244dc0

### Reproduction steps

Playing Enigmatica 2 modpack (not expert mode) on singleplayer.

1. Add Galaticraft-1.12.2-4.0.6 to mods file
2. Attempt to load minecraft
3. After about a minute, the game crashes with the message, "The game crashed whilst initializing game Error: java.lang.IllegalStateException: The fluid registry is corrupted     Exit Code: -1

**Comment by ROMVoid95** [comment]
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/42848897/aaab2c9a-94d9-4285-a1fa-1315c5f01c17)

`[05:02:49] [Client thread/ERROR]: The fluid registry is corrupted. A fluid landmaster.plustic.fluids.FluidMolten titanium is not properly registered. The mod that registered this is broken`

modpack is heavily specific and built with almost every mod scrutinized. I don't recommend adding mods to these type of modpacks (example: types like SevTech, This one).  Even if it is GC that causes this issue to manifest, I will not be going on a search of the root cause when dealing with this many mods and whatever changed/modified configs the pack makes to them. Sorry.
