### ISSUE TITLE
Dehydrated/Canned foods wont give can back if you already have can

### ISSUE THREAD

**Issue by IO2I** [TeamGalacticraft/Galacticraft-Legacy#60]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Reproduction steps

1. Obtain Dehydrated/Canned food
2. Eat Dehydrated/Canned food with an empty can in inventory
3. Receive nothing and be sad that you lost 7 tin ingots.

**Comment by ROMVoid95** [comment]
Performing the exact steps in a new instance with just GC installed, and a tin can is added to my inventory slot one was in every time I ate a canned food, If you can provide any further information I will reopen this.

**Comment by RConTRS** [comment]
it's pretty annoying that canned food drops tin can when consumed, especially when in critical situation or danger, i lost so many tin ingots due to this

i hope making it so if consuming canned food just add tin can to the inventory directly, it just drop like normal if the inventory is full without containing a tin can
